name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install .[dev]
      - name: Cache project
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-project-${{ github.sha }}

  checks:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - name: black
            command: black --check src tests
          - name: isort
            command: isort --check --profile=black --float-to-top src tests
          - name: pylint
            command: pylint -E ./src ./tests
          - name: pytest
            command: pytest tests
          - name: mypy
            command: mypy --strict src tests
    
    steps:
      - name: Get cached project
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-project-${{ github.sha }}
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.command }}

  summary:
    needs: checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.checks.result }}" == "success" ]]; then
            echo "✅ All checks passed!"
          else
            echo "❌ Some checks failed. Please review the logs for details."
            exit 1
          fi
